env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WlDHJiXKcBaiWfA4EJKyG+EMHuv6pX425RMa4f+dotYXqQ13tBhI351R6JsIn7QVMPei+ZFMq8iLx6qhonRKNHUklyJfXSytrJi2NPFmrYgzDHnNT03MkihKd/2fNyCpkrQNKsbfjaVdNq/ZrT01qwyvEapUWol5Kvzx6nyEWhmNyN/j9Sun92amBPqnQ2RrwW/LXPX4j8BRqtwMerQV8vPGIptWbfjpkKdx66/00adaQGn6MUE1Fb/xUbrU/JMDQags81uis3Lez7U5Vrms5s6oufPFojSui5ar9CiP94La6wP7r5Gpa8+vy/MMNRgPrvR1NmNk8VuGGwHNFx428Gpkl7BZha/vPfp0Aw+xZqn/KBb354SXPIdu9Xd6esxjHgTrG2T1CDKaf5O4ah3XCSKf9SRb8uoHBa28v+Al759lBR5z/cRTLWdivUOKiOvPEgoBOWt8+hkzdVjgvv8CJ5Rx7iXP9fGKs32kTU4UhNER+Q6hoOZBReDSb2qW4NX/HieI7AIG8OUmjhJgDYxLSMyFgDHF7Fpv/FiKm6Z10L9hEFlDLX9ENiSbgpgHPfMDNYOS/b3lm8/FcpVfGIBx+MsCuvbDprncuGjwOop3FS0pC/weOSR9IgGTKoSPuV5VpYtCyVor9tUp01bZ3cURb0d6lPoeCK9l30WMwDiqiyw="

language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
  coverity_scan:
    project:
      name: "DanielChappuis/reactphysics3d"
      description: "Build submitted via Travis CI"
    notification_email: chappuis.daniel@gmail.com
    build_command_prepend: "mkdir build_directory; cd build_directory; cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug —DDOUBLE_PRECISION_ENABLED=False ../"
    build_command: "make"
    branch_pattern: develop
branches:
  only:
    - master
    - develop
script:
  - pwd
  - cd build_directory
  # Build in debug mode with double precision
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug —DDOUBLE_PRECISION_ENABLED=True -DCOMPILE_TESTS=True ../
  - make && make test ARGS="-V"
  # Build in debug mode with single precision
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug —DDOUBLE_PRECISION_ENABLED=False -DCOMPILE_TESTS=True ../
  - make && make test ARGS="-V"
  # Build in release mode with double precision
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release —DDOUBLE_PRECISION_ENABLED=True -DCOMPILE_TESTS=True ../
  - make && make test ARGS="-V"
  # Build in release mode with single precision
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release —DDOUBLE_PRECISION_ENABLED=False -DCOMPILE_TESTS=True ../
  - make && make test ARGS="-V"
